# Generated by Django 3.0.5 on 2020-05-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20200504_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(help_text='Название статьи', max_length=200, verbose_name='название статьи'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(help_text='Имя автора комментария', max_length=50, verbose_name='имя автора'),
        ),
    ]
